CREATE DATABASE PETS;
USE PETS;

CREATE TABLE PETS.DOGS (
    DOG_ID INT PRIMARY KEY,
    BREED_NAME VARCHAR (50) NOT NULL,
    BREED_LIFE INT NOT NULL
);

INSERT INTO DOGS (DOG_ID,BREED_NAME,BREED_LIFE)
VALUES (1, 'CORGI', 12);

INSERT INTO DOGS (DOG_ID,BREED_NAME,BREED_LIFE)
VALUES (2, 'CHIHUAHUA', 10);

INSERT INTO DOGS (DOG_ID,BREED_NAME,BREED_LIFE)
VALUES (3, 'PITBULL', 15);

INSERT INTO DOGS (DOG_ID,BREED_NAME,BREED_LIFE)
VALUES (4, 'GOLDEN RETRIEVER', 7);

INSERT INTO DOGS (DOG_ID,BREED_NAME,BREED_LIFE)
VALUES (5, 'PUG', 15);

select * from PETS.DOGS;
